FROM jupyter/scipy-notebook         # base image

RUN pip install joblib              # to serialize and deserialize model

RUN mkdir model                     # same as /home/jovyan/model
ENV MODEL_DIR=/home/jovyan/model
ENV MODEL_FILE=clf.joblib
ENV METADATA_FILE=metadata.json

# copy scripts from local to image
COPY train.py ./train.py
COPY inference.py ./inference.py

RUN python3 train.py                # run model and save model at build time